FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt
RUN pip uninstall antlr4-python3-runtime -y && pip uninstall antlr-python-runtime -y && pip install antlr4-python3-runtime==4.11


COPY . .

CMD ["python3", "main.py"]